sudo: false
language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - ruby-head
cache: bundler
before_install: gem install bundler -v 1.11.2
bundler_args: "--without development"
script: bundle exec rake speclanguage: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.11.2
